#!/bin/sh

set -eu

WALLPAPER_PATH="${1:-${WALLPAPER:-}}"

if [ -z "$WALLPAPER_PATH" ] || [ ! -f "$WALLPAPER_PATH" ]; then
	exit 0
fi

if ! command -v matugen >/dev/null 2>&1; then
	exit 0
fi

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/matugen"
JSON_PATH="$CACHE_DIR/colors-dark.json"
TMP_JSON="$JSON_PATH.tmp"

mkdir -p "$CACHE_DIR"

if ! matugen image "$WALLPAPER_PATH" -m dark -t scheme-tonal-spot -j hex -q > "$TMP_JSON"; then
	rm -f "$TMP_JSON"
	exit 0
fi

mv "$TMP_JSON" "$JSON_PATH"

python3 - "$JSON_PATH" <<'PY'
import json
import os
import pathlib
import sys

json_path = pathlib.Path(sys.argv[1])
data = json.loads(json_path.read_text())
colors = data.get("colors", {})

def c(name, fallback="#ffffff"):
    value = colors.get(name, {}).get("default", fallback)
    if not isinstance(value, str) or not value.startswith("#") or len(value) != 7:
        return fallback
    return value.lower()

def rgba(hex_rgb, alpha):
    return f"{hex_rgb}{alpha}"

def nohash(hex_rgb):
    return hex_rgb.lstrip("#")

home = pathlib.Path(os.environ["HOME"])
tofi = home / ".config/tofi/config"
mako = home / ".config/mako/config"
swaylock = home / ".config/swaylock/config"
palette = home / ".cache/matugen/palette.sh"

surface = c("surface", "#1e1e1e")
surface_container = c("surface_container", "#2a2a2a")
surface_variant = c("surface_variant", "#3a3a3a")
outline = c("outline", "#666666")
primary = c("primary", "#88c0d0")
secondary = c("secondary", "#a3be8c")
tertiary = c("tertiary", "#b48ead")
on_surface = c("on_surface", "#eceff4")
on_primary = c("on_primary", "#1f1f1f")
error = c("error", "#bf616a")

tofi.parent.mkdir(parents=True, exist_ok=True)
tofi.write_text(
    "\n".join([
        "# Auto-generated by ~/.config/dwl/matugen-theme.sh",
        "font = \"Iosevka 16\"",
        "prompt-text = \"run: \"",
        "drun-launch = true",
        "terminal = \"alacritty\"",
        "width = 40%",
        "height = 40%",
        "anchor = center",
        "outline-width = 2",
        "border-width = 6",
        "corner-radius = 10",
        "padding-top = 8",
        "padding-bottom = 8",
        "padding-left = 12",
        "padding-right = 12",
        "result-spacing = 6",
        "",
        f"background-color = {surface}",
        f"outline-color = {surface_variant}",
        f"border-color = {outline}",
        f"text-color = {on_surface}",
        f"prompt-color = {primary}",
        f"input-color = {on_surface}",
        f"placeholder-color = {outline}",
        f"selection-color = {on_primary}",
        f"selection-background = {primary}",
        f"selection-match-color = {on_primary}",
        "selection-background-padding = 2,8",
        "",
        f"default-result-color = {on_surface}",
        f"alternate-result-color = {on_surface}",
        "",
    ])
)

mako.parent.mkdir(parents=True, exist_ok=True)
mako.write_text(
    "\n".join([
        "font=monospace 11",
        f"background-color={rgba(surface, 'dd')}",
        f"text-color={rgba(on_surface, 'ff')}",
        f"border-color={rgba(primary, 'ff')}",
        f"progress-color=over {rgba(surface_variant, 'ff')}",
        "border-size=2",
        "border-radius=8",
        "padding=10",
        "default-timeout=5000",
        "ignore-timeout=1",
        "anchor=top-right",
        "max-visible=5",
        "layer=overlay",
        "",
        "[urgency=high]",
        f"background-color={rgba(surface_container, 'ee')}",
        f"text-color={rgba(error, 'ff')}",
        f"border-color={rgba(error, 'ff')}",
        "default-timeout=0",
        "",
    ])
)

swaylock.parent.mkdir(parents=True, exist_ok=True)
swaylock.write_text(
    "\n".join([
        "ignore-empty-password",
        "",
        "font=monospace",
        "indicator-radius=96",
        "indicator-thickness=10",
        "",
        f"inside-color={nohash(rgba(surface, 'cc'))}",
        f"ring-color={nohash(rgba(primary, 'ff'))}",
        "line-color=00000000",
        f"key-hl-color={nohash(rgba(on_surface, 'ff'))}",
        "separator-color=00000000",
        f"text-color={nohash(rgba(on_surface, 'ff'))}",
        "",
        f"inside-clear-color={nohash(rgba(surface_container, 'cc'))}",
        f"ring-clear-color={nohash(rgba(secondary, 'ff'))}",
        f"text-clear-color={nohash(rgba(on_surface, 'ff'))}",
        "",
        f"inside-ver-color={nohash(rgba(surface_container, 'cc'))}",
        f"ring-ver-color={nohash(rgba(tertiary, 'ff'))}",
        f"text-ver-color={nohash(rgba(on_surface, 'ff'))}",
        "",
        f"inside-wrong-color={nohash(rgba(surface_container, 'cc'))}",
        f"ring-wrong-color={nohash(rgba(error, 'ff'))}",
        f"text-wrong-color={nohash(rgba(error, 'ff'))}",
        "",
    ])
)

palette.parent.mkdir(parents=True, exist_ok=True)
palette.write_text(
    "\n".join([
        "# Generated by matugen-theme.sh",
        f"export MATUGEN_SURFACE='{surface}'",
        f"export MATUGEN_SURFACE_CONTAINER='{surface_container}'",
        f"export MATUGEN_SURFACE_VARIANT='{surface_variant}'",
        f"export MATUGEN_OUTLINE='{outline}'",
        f"export MATUGEN_PRIMARY='{primary}'",
        f"export MATUGEN_SECONDARY='{secondary}'",
        f"export MATUGEN_TERTIARY='{tertiary}'",
        f"export MATUGEN_ON_SURFACE='{on_surface}'",
        f"export MATUGEN_ON_PRIMARY='{on_primary}'",
        f"export MATUGEN_ERROR='{error}'",
        "",
    ])
)
PY

if pgrep -x mako >/dev/null 2>&1; then
	pkill -x mako >/dev/null 2>&1 || true
	mako >/dev/null 2>&1 &
fi
